# Generated by Django 2.1.5 on 2019-02-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='total_sujet',
            field=models.IntegerField(default=0),
        ),
    ]
