# Generated by Django 2.1.5 on 2019-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0007_remove_reponse_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='utilisateur_cin',
            field=models.CharField(default='CIN', max_length=8),
        ),
    ]
