# Generated by Django 2.1.5 on 2019-02-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0008_utilisateur_utilisateur_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='Departement',
            field=models.CharField(default='Null', max_length=40),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(default='email', max_length=10),
        ),
    ]
