# Generated by Django 2.1.5 on 2019-02-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0009_auto_20190223_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='complete',
            field=models.IntegerField(default=0),
        ),
    ]
