# Generated by Django 2.1.5 on 2019-02-23 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0011_auto_20190223_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='id',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
