# Generated by Django 2.1.5 on 2019-02-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0012_auto_20190223_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='topic',
            new_name='Subject',
        ),
    ]
