# Generated by Django 2.1.5 on 2019-02-24 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0013_auto_20190224_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='annedenaissance',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='cne',
            field=models.CharField(default='cne', max_length=10),
        ),
    ]
