# Generated by Django 2.1.5 on 2019-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0015_auto_20190224_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='total_sujet',
        ),
        migrations.AddField(
            model_name='departement',
            name='Code_filiere',
            field=models.CharField(default='default', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='departement',
            field=models.CharField(default='default', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='description',
            field=models.CharField(default='default', max_length=30, unique=True),
        ),
    ]
