# Generated by Django 2.1.5 on 2019-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0016_auto_20190225_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='Code_filiere',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='departement',
            name='departement',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='departement',
            name='description',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
