# Generated by Django 2.1.5 on 2019-02-25 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0017_auto_20190225_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='Code_filiere',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='description',
        ),
        migrations.AddField(
            model_name='departement',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departement',
            name='total_sujet',
            field=models.IntegerField(default=0),
        ),
    ]
