# Generated by Django 2.1.5 on 2019-02-25 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0018_auto_20190225_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='name',
            new_name='Code_filiere',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='total_sujet',
        ),
        migrations.AddField(
            model_name='departement',
            name='departement',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departement',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
