# Generated by Django 2.1.5 on 2019-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0020_auto_20190225_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='annedenaissance',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='img',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Filiere',
            field=models.CharField(default=0, max_length=80),
        ),
    ]
