# Generated by Django 2.1.5 on 2019-02-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0022_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='forumestc.theme'),
        ),
    ]
