# Generated by Django 2.1.5 on 2019-02-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(max_length=4)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PE.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PE.matiere')),
            ],
        ),
    ]
