# Generated by Django 2.1.5 on 2019-02-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('club', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
