# Generated by Django 2.1.5 on 2019-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0003_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
