# Generated by Django 2.1.5 on 2019-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0006_evenement_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='text',
        ),
        migrations.AddField(
            model_name='evenement',
            name='description',
            field=models.TextField(default='defaultText'),
        ),
    ]
