# Generated by Django 2.1.5 on 2019-02-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0001_initial'),
        ('PE', '0009_auto_20190214_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='elecetion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidat_allname', models.CharField(max_length=40)),
                ('candidat_totalvote', models.IntegerField(default=0)),
                ('candidat_img', models.ImageField(upload_to='')),
                ('candidat_voter', models.CharField(max_length=50)),
                ('candidat_departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumestc.Departement')),
            ],
        ),
    ]
