# Generated by Django 2.1.5 on 2019-02-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumestc', '0001_initial'),
        ('PE', '0010_elecetion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='elecetion',
            new_name='candidat_president',
        ),
    ]
