# Generated by Django 2.1.5 on 2019-02-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0013_auto_20190214_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualité',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
