# Generated by Django 2.1.5 on 2019-02-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0014_auto_20190216_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat_president',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='candidat_president',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='candidat_president',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
