# Generated by Django 2.1.5 on 2019-02-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0015_auto_20190223_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat_president',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='candidat_president',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='candidat_president',
            name='vote_score',
        ),
    ]
