# Generated by Django 2.1.5 on 2019-02-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0016_auto_20190223_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electeur',
            old_name='candidat_cin',
            new_name='electeur_cin',
        ),
    ]
