# Generated by Django 2.1.5 on 2019-02-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0017_auto_20190224_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_apogee', models.CharField(default=0, max_length=8)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('CIN', models.CharField(max_length=10)),
                ('Filiere', models.CharField(default=0, max_length=80)),
                ('cne', models.CharField(max_length=10)),
                ('complete', models.IntegerField(default=0)),
            ],
        ),
    ]
