# Generated by Django 2.1.5 on 2019-02-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0018_etudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electeur',
            name='electeur_departement',
        ),
    ]
